ALTER EXTENSION plsh ADD PROCEDURAL LANGUAGE plsh;
ALTER EXTENSION plsh ADD FUNCTION plsh_handler();
ALTER EXTENSION plsh ADD FUNCTION plsh_validator(oid);

ALTER EXTENSION plsh ADD PROCEDURAL LANGUAGE plsh2;
ALTER EXTENSION plsh ADD FUNCTION plsh2_handler();
ALTER EXTENSION plsh ADD FUNCTION plsh2_validator(oid);
